package com.demo.dao.model;

public class RoleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.role_code
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.role_pid
     *
     * @mbggenerated
     */
    private String rolePid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.role_desc
     *
     * @mbggenerated
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.role_type
     *
     * @mbggenerated
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role_info.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_role_info
     *
     * @mbggenerated
     */
    public RoleInfo(String id, String roleName, String roleCode, String rolePid, String roleDesc, String roleType, String sort, String status, String createTime, String createBy, String updateTime, String updateBy) {
        this.id = id;
        this.roleName = roleName;
        this.roleCode = roleCode;
        this.rolePid = rolePid;
        this.roleDesc = roleDesc;
        this.roleType = roleType;
        this.sort = sort;
        this.status = status;
        this.createTime = createTime;
        this.createBy = createBy;
        this.updateTime = updateTime;
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.id
     *
     * @return the value of b_role_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.role_name
     *
     * @return the value of b_role_info.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.role_code
     *
     * @return the value of b_role_info.role_code
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.role_pid
     *
     * @return the value of b_role_info.role_pid
     *
     * @mbggenerated
     */
    public String getRolePid() {
        return rolePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.role_desc
     *
     * @return the value of b_role_info.role_desc
     *
     * @mbggenerated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.role_type
     *
     * @return the value of b_role_info.role_type
     *
     * @mbggenerated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.sort
     *
     * @return the value of b_role_info.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.status
     *
     * @return the value of b_role_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.create_time
     *
     * @return the value of b_role_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.create_by
     *
     * @return the value of b_role_info.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.update_time
     *
     * @return the value of b_role_info.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role_info.update_by
     *
     * @return the value of b_role_info.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }
}