package com.demo.dao.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.user_sign
     *
     * @mbggenerated
     */
    private String userSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.head_img
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user_info.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user_info
     *
     * @mbggenerated
     */
    public UserInfo(String id, String account, String realName, String nickName, String password, String userSign, String phone, String email, Byte gender, Integer userType, String headImg, Byte status, String createTime, String createBy, String updateTime, String updateBy) {
        this.id = id;
        this.account = account;
        this.realName = realName;
        this.nickName = nickName;
        this.password = password;
        this.userSign = userSign;
        this.phone = phone;
        this.email = email;
        this.gender = gender;
        this.userType = userType;
        this.headImg = headImg;
        this.status = status;
        this.createTime = createTime;
        this.createBy = createBy;
        this.updateTime = updateTime;
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.id
     *
     * @return the value of b_user_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.account
     *
     * @return the value of b_user_info.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.real_name
     *
     * @return the value of b_user_info.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.nick_name
     *
     * @return the value of b_user_info.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.password
     *
     * @return the value of b_user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.user_sign
     *
     * @return the value of b_user_info.user_sign
     *
     * @mbggenerated
     */
    public String getUserSign() {
        return userSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.phone
     *
     * @return the value of b_user_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.email
     *
     * @return the value of b_user_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.gender
     *
     * @return the value of b_user_info.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.user_type
     *
     * @return the value of b_user_info.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.head_img
     *
     * @return the value of b_user_info.head_img
     *
     * @mbggenerated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.status
     *
     * @return the value of b_user_info.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.create_time
     *
     * @return the value of b_user_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.create_by
     *
     * @return the value of b_user_info.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.update_time
     *
     * @return the value of b_user_info.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user_info.update_by
     *
     * @return the value of b_user_info.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }
}