package com.demo.dao.mapper;

import com.demo.dao.model.RoleInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_role_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from b_role_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_role_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into b_role_info (id, role_name, ",
        "role_code, role_pid, ",
        "role_desc, role_type, ",
        "sort, status, create_time, ",
        "create_by, update_time, ",
        "update_by)",
        "values (#{id,jdbcType=VARCHAR}, #{roleName,jdbcType=VARCHAR}, ",
        "#{roleCode,jdbcType=VARCHAR}, #{rolePid,jdbcType=VARCHAR}, ",
        "#{roleDesc,jdbcType=VARCHAR}, #{roleType,jdbcType=VARCHAR}, ",
        "#{sort,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{createBy,jdbcType=VARCHAR}, #{updateTime,jdbcType=VARCHAR}, ",
        "#{updateBy,jdbcType=VARCHAR})"
    })
    int insert(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_role_info
     *
     * @mbggenerated
     */
    int insertSelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_role_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, role_name, role_code, role_pid, role_desc, role_type, sort, status, create_time, ",
        "create_by, update_time, update_by",
        "from b_role_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    RoleInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_role_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_role_info
     *
     * @mbggenerated
     */
    @Update({
        "update b_role_info",
        "set role_name = #{roleName,jdbcType=VARCHAR},",
          "role_code = #{roleCode,jdbcType=VARCHAR},",
          "role_pid = #{rolePid,jdbcType=VARCHAR},",
          "role_desc = #{roleDesc,jdbcType=VARCHAR},",
          "role_type = #{roleType,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "update_by = #{updateBy,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RoleInfo record);
}